#
# ChangeLog for tinymce-advanced/tags/5.5.1/mce/anchor/plugin.js
#
# Generated by Trac 1.2.2
# 02/10/2022 12:45:41 AM

Tue, 29 Sep 2020 10:06:16 GMT azaozz [2390184]
	* tinymce-advanced/tags/5.5.1 (copied)

	Tag 5.5.1


Mon, 20 May 2019 04:08:53 GMT azaozz [2091071]
	* tinymce-advanced/trunk/block-editor (added)
	* tinymce-advanced/trunk/block-editor/classic-paragraph.css (added)
	* tinymce-advanced/trunk/block-editor/classic-paragraph.js (added)
	* tinymce-advanced/trunk/block-editor/richtext-buttons.css (added)
	* tinymce-advanced/trunk/block-editor/richtext-buttons.js (added)
	* tinymce-advanced/trunk/block-editor/tma-block-editor.css (added)
	* tinymce-advanced/trunk/css (deleted)
	* tinymce-advanced/trunk/dist (deleted)
	* tinymce-advanced/trunk/images (deleted)
	* tinymce-advanced/trunk/js (deleted)
	* tinymce-advanced/trunk/mce/advlist/plugin.js (modified)
	* tinymce-advanced/trunk/mce/anchor/plugin.js (modified)
	* tinymce-advanced/trunk/mce/code/plugin.js (modified)
	* tinymce-advanced/trunk/mce/contextmenu/plugin.js (modified)
	* tinymce-advanced/trunk/mce/importcss/plugin.js (modified)
	* tinymce-advanced/trunk/mce/importcss/plugin.min.js (modified)
	* tinymce-advanced/trunk/mce/insertdatetime/plugin.js (modified)
	* tinymce-advanced/trunk/mce/link/plugin.js (modified)
	* tinymce-advanced/trunk/mce/link/plugin.min.js (modified)
	* tinymce-advanced/trunk/mce/nonbreaking/plugin.js (modified)
	* tinymce-advanced/trunk/mce/print/plugin.js (modified)
	* tinymce-advanced/trunk/mce/searchreplace/plugin.js (modified)
	* tinymce-advanced/trunk/mce/searchreplace/plugin.min.js (modified)
	* tinymce-advanced/trunk/mce/table/plugin.js (modified)
	* tinymce-advanced/trunk/mce/table/plugin.min.js (modified)
	* tinymce-advanced/trunk/mce/visualblocks/plugin.js (modified)
	* tinymce-advanced/trunk/mce/visualchars/plugin.js (modified)
	* tinymce-advanced/trunk/mce/visualchars/plugin.min.js (modified)
	* tinymce-advanced/trunk/mce/wptadv/plugin.js (modified)
	* tinymce-advanced/trunk/mce/wptadv/plugin.min.js (modified)
	* tinymce-advanced/trunk/plugin-assets (added)
	* tinymce-advanced/trunk/plugin-assets/images (added)
	* tinymce-advanced/trunk/plugin-assets/images/colors-rtl.png (added)
	* tinymce-advanced/trunk/plugin-assets/images/colors.png (added)
	* tinymce-advanced/trunk/plugin-assets/images/toolbar-actions-rtl.png (added)
	* tinymce-advanced/trunk/plugin-assets/images/toolbar-actions.png (added)
	* tinymce-advanced/trunk/plugin-assets/tadv.css (added)
	* tinymce-advanced/trunk/plugin-assets/tadv.js (added)
	* tinymce-advanced/trunk/readme.txt (modified)
	* tinymce-advanced/trunk/tadv_admin.php (modified)
	* tinymce-advanced/trunk/tinymce-advanced.php (modified)

	TMA: update for WP 5.2.1


