#
# ChangeLog for tinymce-advanced/tags/5.5.1/mce/anchor/plugin.min.js
#
# Generated by Trac 1.2.2
# 02/10/2022 04:08:27 PM

Tue, 29 Sep 2020 10:06:16 GMT azaozz [2390184]
	* tinymce-advanced/tags/5.5.1 (copied)

	Tag 5.5.1


Mon, 21 May 2018 11:39:54 GMT azaozz [1878362]
	* tinymce-advanced/trunk/mce/anchor/plugin.js (modified)
	* tinymce-advanced/trunk/mce/anchor/plugin.min.js (modified)
	* tinymce-advanced/trunk/mce/table/plugin.js (modified)
	* tinymce-advanced/trunk/mce/table/plugin.min.js (modified)
	* tinymce-advanced/trunk/readme.txt (modified)
	* tinymce-advanced/trunk/tinymce-advanced.php (modified)

	Update plugins to 4.7.13.


